name: billie
description: Music Streaming app made in Flutter!
homepage: https://github.com/gokadzev/Musify
repository: https://github.com/gokadzev/Musify
issue_tracker: https://github.com/gokadzev/Musify/issues

publish_to: 'none'
version: 1.0.0+1 # run update.sh after changing the version

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  audio_service: ^0.18.17
  audio_session: ^0.1.21
  cached_network_image: ^3.4.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_flip_card: ^0.0.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.7
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.6
  http: ^1.5.0
  infinite_scroll_pagination: ^5.1.1
  intl: any
  just_audio: ^0.9.39
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  url_launcher: ^6.2.0
  youtube_explode_dart: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  translations_cleaner: ^0.0.5

  # flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/licenses/
    - assets/images/

  fonts:
    - family: paytoneOne
      fonts:
        - asset: fonts/paytone/PaytoneOne-Regular.ttf
